Bump dependencies to the latest available versions.
Exception: don't update httpx, because of this issue: https://github.com/tiangolo/fastapi/discussions/6211#discussioncomment-8815439