Fix bug when refreshing oauth token in withings.
We were missing an `await` in the requests post wrapper.
```
        response = await requests.post(
            db,
            user=user,
            url=f"{settings.withings_base_url}measure",
            data={
                "action": "getmeas",
                "meastype": 1,  # weight
                "category": 1,  # real measures, not objectives
                "startdate": startdate,
                "enddate": enddate,
            },
        )
>       response_data = response.json()["body"]
E       AttributeError: 'coroutine' object has no attribute 'json'
```